services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: verilec
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d verilec"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+asyncpg://user:pass@db/verilec
      LOCAL_STORAGE_DIR: /app/storage
      PIPELINE_ROOT: /app

      # GPU 1번만 컨테이너에 노출
      NVIDIA_VISIBLE_DEVICES: "1"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"

      # VeriLec / GraphLec GPU decode 설정
      GRAPHLEC_SLIDE_DECODE_BACKEND: ffmpeg-cuda
      GRAPHLEC_GPU_ONLY: "0"

      # Ultralytics / matplotlib 경고 방지용
      YOLO_CONFIG_DIR: /tmp/Ultralytics
      MPLCONFIGDIR: /tmp/matplotlib

      # Step 0 sample cache chunk 병렬화
      GRAPHLEC_SAMPLE_CACHE_CHUNK_WORKERS: "12"
      GRAPHLEC_SAMPLE_CACHE_CHUNK_SEC: "300"
      GRAPHLEC_SAMPLE_CACHE_CHUNK_OVERLAP_SEC: "30"
      GRAPHLEC_SAMPLE_CACHE_MERGE_WORKERS: "6"
      GRAPHLEC_SAMPLE_CACHE_MERGE_MASK_WORKERS: "12"

      #STEP 1 worker 설정
      GRAPHLEC_REGION_WORKERS: "12"
      GRAPHLEC_REGION_CHUNK_SAMPLES: "2000"
      GRAPHLEC_REGION_CUARD_SAMPLE: "1"

    volumes:
      - ./storage:/app/storage
      - ./input:/app/input

    ports:
      - "8003:8000"
    depends_on:
      db:
        condition: service_healthy

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

volumes:
  postgres_data:
